- name: Disable swap
  shell: swapoff -a

- name: Disable swap permanently (modify /etc/fstab)
  replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)$'
    backup: yes
    replace: '#\1'

- name: set net.ipv4.ip_forward to 1
  retries: 2
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present

- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Kubernetes' APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: "Install kubeadm and dependencies"
  apt:
    pkg:
      - kubelet={{ kubernetes_version }}
      - kubeadm={{ kubernetes_version }}
      - kubectl={{ kubernetes_version }}
    state: present

- name: Create the directory for the manual storage class
  file:
    path: /opt/k8s-manual
    state: directory
    mode: '0755'