# depending on this check, cluster init and following steps are skipped
- name: check if kubernetes is already initialized
  stat: 
    path: /etc/kubernetes/admin.conf
  register: k8s_is_installed

# initialize cluster
- name: initialize the cluster
  # pod cidr is for calico, could be made available via inventory
  shell: "kubeadm init --pod-network-cidr={{ pod_network_cidr }} --token {{ kubeadm_token }}"
  # skipping task if kubernetes is already initialzed
  when: not k8s_is_installed.stat.exists

# if we don't wait here a little while, anislbe will fail the copy job below
# due to missing file, since it is still creating by then
- name: Wait until the file /etc/kubernetes/admin.conf is present before continuing
  wait_for:
    path: /etc/kubernetes/admin.conf
    timeout: 20
    delay: 10
    msg: Timeout to find file /etc/kubernetes/admin.conf
  # skipping task if kubernetes is already initialzed
  when: not k8s_is_installed.stat.exists

# create kubectl config folder for user ubuntu
- name: create .kube directory for user ubuntu
  file:
    path: /home/ubuntu/.kube
    state: directory
    mode: 0755
    owner: ubuntu
  # skipping task if kubernetes is already initialzed
  when: not k8s_is_installed.stat.exists

# make kubectl work without setting kubeconfig via env
- name: copy admin.conf to user home folder
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    owner: ubuntu
    remote_src: yes
  # skipping task if kubernetes is already initialzed
  when: not k8s_is_installed.stat.exists

# create kubectl config folder for user root
- name: create .kube directory for user root
  file:
    path: /root/.kube
    state: directory
    mode: 0755
  # skipping task if kubernetes is already initialzed
  when: not k8s_is_installed.stat.exists

# make kubectl work without setting kubeconfig via env
- name: copy admin.conf to root user home folder
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
  # skipping task if kubernetes is already initialzed
  when: not k8s_is_installed.stat.exists